### ISSUE TITLE
Feature Request - Factoids

### ISSUE THREAD

**Issue by patchys** [remiscarlet/RandomKCWikiScripts#2]
The ability to create a factoid. Example: Inputting !Mumble returns a stored variable entered earlier.

**Comment by remiscarlet** [comment]
Will do when I'm not rolling around in bed

**Comment by remiscarlet** [comment]
Added in https://github.com/remiscarlet/RandomKCWikiScripts/commit/63b7f92c74b3a753b1dedb75b4a3ab71b8789396
